default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sakila_rails_development

test:
  <<: *default
  database: sakila_rails_test

production:
  <<: *default
  database: sakila_rails_production
  username: sakila_rails
  password: <%= ENV["SAKILA_RAILS_DATABASE_PASSWORD"] %>
